blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from .apps import BlogConfig
from .views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
    BlogListViewAll,
)

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60*15)(BlogListView.as_view()), name='blog_list'),  # Кэш на 15 минут
    path('listAll/', cache_page(60*15)(BlogListViewAll.as_view()), name='blog_list_all'),
    path('<int:pk>/', cache_page(60*15)(BlogDetailView.as_view()), name='blog_detail'),
    path('create/', never_cache(BlogCreateView.as_view()), name='blog_create'),
    path('<int:pk>/update/', never_cache(BlogUpdateView.as_view()), name='blog_update'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from .views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, MessageListView, \
    MessageCreateView, MessageUpdateView, MessageDeleteView, MailingListView, MailingCreateView, MailingUpdateView, \
    MailingDeleteView, AttemptListView, home
from mailing.apps import MailingConfig

app_name = MailingConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('clients/', ClientListView.as_view(), name='client-list'),
    path('clients/create/', ClientCreateView.as_view(), name='client-create'),
    path('clients/<int:pk>/update/', ClientUpdateView.as_view(), name='client-update'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client-delete'),
    path('message/', MessageListView.as_view(), name='message-list'),
    path('message/create/', MessageCreateView.as_view(), name='message-create'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message-update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message-delete'),
    path('mailings/', MailingListView.as_view(), name='mailing-list'),
    path('mailings/create/', MailingCreateView.as_view(), name='mailing-create'),
    path('mailings/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing-update'),
    path('mailings/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing-delete'),
    path('attempt/', AttemptListView.as_view(), name='attempt-list'),

]

templates/message/message_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Подтверждение удаления сообещния</title>
    {% include 'includes/style_delete.html' %}
</head>
<body>
<header>
    <h2>Подтверждение удаления сообещния</h2>
</header>
<p>Вы уверены, что хотите удалить сообещния "{{ object.subject }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
    <a href="{% url 'mailing:message-list' %}">
        <button type="button" class="cancel-button">Отмена</button>
    </a>
</form>
{% include 'includes/style.html' %}
</body>
</html>
{% endblock %}

templates/message/message_form.html
{% extends 'base.html' %}

{% block content %}
<div class="form-container">
    <h2>{% if object %}Редактировать{% else %}Добавить{% endif %} сообщение</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit-button">Сохранить</button>
    </form>
    <a class="back-link" href="{% url 'mailing:message-list' %}">Назад к списку сообщений</a>
</div>

{% include 'includes/style.html' %}
{% endblock %}

templates/message/message_list.html
{% extends 'base.html' %}

{% block content %}
<html>
<body>
<!-- Основное содержимое -->
<div class="main-content">
    <div class="container">
        <h2>Список сообщений</h2>
        <a href="{% url 'mailing:message-create' %}">Создать новое сообщение</a>
            <ul class="message-list">
                {% for message in message %}
                <li class="message-item">
                    {{ message.subject }}
                    <a href="{% url 'mailing:message-update' message.pk %}" class="edit-link">Редактировать</a>
                    <a href="{% url 'mailing:message-delete' message.pk %}" class="delete-link">Удалить</a>
                </li>
                {% endfor %}
            </ul>
    </div>
    {% endblock %}