blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from .apps import BlogConfig
from .views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
    BlogListViewAll,
)

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60*15)(BlogListView.as_view()), name='blog_list'),  # Кэш на 15 минут
    path('listAll/', cache_page(60*15)(BlogListViewAll.as_view()), name='blog_list_all'),
    path('<int:pk>/', cache_page(60*15)(BlogDetailView.as_view()), name='blog_detail'),
    path('create/', never_cache(BlogCreateView.as_view()), name='blog_create'),
    path('<int:pk>/update/', never_cache(BlogUpdateView.as_view()), name='blog_update'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from .views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, MessageListView, \
    MessageCreateView, MessageUpdateView, MessageDeleteView, MailingListView, MailingCreateView, MailingUpdateView, \
    MailingDeleteView, AttemptListView, home
from mailing.apps import MailingConfig

app_name = MailingConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('clients/', ClientListView.as_view(), name='client-list'),
    path('clients/create/', ClientCreateView.as_view(), name='client-create'),
    path('clients/<int:pk>/update/', ClientUpdateView.as_view(), name='client-update'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client-delete'),
    path('message/', MessageListView.as_view(), name='message-list'),
    path('message/create/', MessageCreateView.as_view(), name='message-create'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message-update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message-delete'),
    path('mailings/', MailingListView.as_view(), name='mailing-list'),
    path('mailings/create/', MailingCreateView.as_view(), name='mailing-create'),
    path('mailings/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing-update'),
    path('mailings/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing-delete'),
    path('attempt/', AttemptListView.as_view(), name='attempt-list'),

]

templates/base.html
<!DOCTYPE html>
<html lang="ru">

{% include 'includes/inc_menu.html' %}
{% include 'includes/head.html' %}

<body style="margin: 0; font-family: Arial, sans-serif; background-color: #f4f4f4;">
<header style="display: flex; flex-direction: column; justify-content: center; align-items: center; height: 150px; background-color: #007BFF; color: white; text-align: center;">
    <h1 style="margin: 0;">Сервис управления рассылками</h1>
</header>
<section
        style="display: flex; flex-direction: column; justify-content: center; align-items: center; padding: 20px; text-align: center;">
    {% if not user.is_authenticated %}
    <h2 style="color: #333; margin-bottom: 20px;">На данном сайте вы можете создавать, контролировать и управлять
        рассылками для информирования и привлечения клиентов!</h2>
    <h3 style="color: #666;">Войдите или зарегистрируйтесь</h3>
    {% endif %}
</section>

{% if user.is_authenticated %}
<nav>
    <ul style="display: flex; justify-content: center; padding: 0; list-style: none;">
        <li style="margin: 0 15px;"><a href="{% url 'mailing:client-list' %}">Клиенты</a></li>
        <li style="margin: 0 15px;"><a href="{% url 'mailing:message-list' %}">Сообщения</a></li>
        <li style="margin: 0 15px;"><a href="{% url 'mailing:mailing-list' %}">Рассылка сообщений</a></li>
        <li style="margin: 0 15px;"><a href="{% url 'mailing:attempt-list' %}">Список попыток</a></li>
        <li style="margin: 0 15px;"><a href="{% url 'blog:blog_list' %}">Блог</a></li>
   </ul>
</nav>
{% endif %}

<main style="display: flex; justify-content: center; align-items: center; padding: 20px;">
    {% block content %}
    <div style="text-align: center; margin: 0 auto;">
    <p>Количество рассылок всего: {{ mailings_count }}</p>
    <p>Количество активных рассылок: {{ mailings_count_active }}</p>
    <p>Количество уникальных клиентов: {{ clients_count }}</p>

<h2>Статьи из блога</h2>
<ul style="list-style: none; padding: 0;">
    {% for blog in articles %}
        <li><a href="{% url 'blog:blog_detail' blog.id %}">{{ blog.title }}</a></li>
    {% endfor %}
</ul>
</div>

    {% endblock %}
</main>

<footer style="display: flex; justify-content: center; align-items: center; height: 50px; background-color: #007BFF; color: white; text-align: center;">
    <p style="margin: 0;">&copy; 2024 Почтовые рассылки</p>
</footer>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        flatpickr('.datetime-picker', {
            enableTime: true,
            dateFormat: 'Y-m-d H:i',
        });
    });
</script>

</body>
</html>