blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from .apps import BlogConfig
from .views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
    BlogListViewAll,
)

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60*15)(BlogListView.as_view()), name='blog_list'),  # Кэш на 15 минут
    path('listAll/', cache_page(60*15)(BlogListViewAll.as_view()), name='blog_list_all'),
    path('<int:pk>/', cache_page(60*15)(BlogDetailView.as_view()), name='blog_detail'),
    path('create/', never_cache(BlogCreateView.as_view()), name='blog_create'),
    path('<int:pk>/update/', never_cache(BlogUpdateView.as_view()), name='blog_update'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from .views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, MessageListView, \
    MessageCreateView, MessageUpdateView, MessageDeleteView, MailingListView, MailingCreateView, MailingUpdateView, \
    MailingDeleteView, AttemptListView, home
from mailing.apps import MailingConfig

app_name = MailingConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('clients/', ClientListView.as_view(), name='client-list'),
    path('clients/create/', ClientCreateView.as_view(), name='client-create'),
    path('clients/<int:pk>/update/', ClientUpdateView.as_view(), name='client-update'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client-delete'),
    path('message/', MessageListView.as_view(), name='message-list'),
    path('message/create/', MessageCreateView.as_view(), name='message-create'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message-update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message-delete'),
    path('mailings/', MailingListView.as_view(), name='mailing-list'),
    path('mailings/create/', MailingCreateView.as_view(), name='mailing-create'),
    path('mailings/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing-update'),
    path('mailings/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing-delete'),
    path('attempt/', AttemptListView.as_view(), name='attempt-list'),

]

templates/clients/client_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Подтверждение удаления клиента</title>
    {% include 'includes/style_delete.html' %}
</head>
<body>
<header>
    <h2>Подтверждение удаления клиента</h2>
</header>
<p>Вы уверены, что хотите удалить клиента "{{ object.full_name }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
    <a href="{% url 'mailing:client-list' %}">
        <button type="button" class="cancel-button">Отмена</button>
    </a>
</form>


{% include 'includes/style.html' %}
</body>
</html>
{% endblock %}

templates/clients/client_create.html
{% extends 'base.html' %}


<html lang="ru">
<body>
   <header>
       <h1>Почтовые рассылки</h1>
   </header>
   <nav>
       <ul>
           <li><a href="{% url 'mailing:client-list' %}">Клиенты</a></li>
           <li><a href="{% url 'mailing:message-list' %}">Сообщения</a></li>
           <li><a href="{% url 'mailing:mailing-list' %}">Рассылка сообщений</a></li>
           <li><a href="{% url 'mailing:attempt-list' %}">Список попыток</a></li>
       </ul>
   </nav>
   <main>
       {% block content %}
       <!-- Основное содержимое страницы будет вставляться здесь -->
       {% endblock %}
   </main>
   <footer>
       <p>&copy; 2024 Почтовые рассылки</p>
   </footer>
</body>
</html>
{% endblock %}

templates/clients/client_form.html
{% extends 'base.html' %}

{% block content %}
<div class="form-container">
    <h2>{% if object %}Редактировать{% else %}Добавить{% endif %} клиента</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
    <a class="back-link" href="{% url 'mailing:client-list' %}">Назад к списку клиентов</a>
</div>

{% include 'includes/style.html' %}
{% endblock %}

templates/clients/client_list.html
{% extends 'base.html' %}

{% block content %}
<html>
<body>
<!-- Основное содержимое -->
<div class="main-content">
    <div class="container">
        <h2>Список клиентов</h2>
        <a href="{% url 'mailing:client-create' %}">Создать нового клиента</a>
        <ul>
            {% for client in clients %}
            <li>
                <strong>{{ client.full_name }}</strong><br>
                {{ client.email }}<br>
                <a href="{% url 'mailing:client-update' client.pk %}">Редактировать</a>
                <a href="{% url 'mailing:client-delete' client.pk %}">Удалить</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
</body>
</html>
{% endblock %}